language: java
after_success: echo $ASDF
env:
  secure: "xMwCJBl52fCXbnFWU52MvidZTOK5CXKwHejFnsnjpYDIjE+koLqqn+KBA8wVADUIjm876ieNSM8w+levVlffYUGPlTa5xB4bGV8rcd1mrK2YBNKCfXimW/+cNUOgZBTKGYnh97lVw1LY2mapBOEB+iS/MDE/g1sBKM/gIxcJSL6wbA9FeH7GwAmde93rQmB6u4XVjzoJXOIyFCsBDRC3GZPOSMI8EUJgVLPnX7EqW4x4bBhImmjosq61K1miqluGNkIXAQDVeS6iaxsbsXGA+fPaUdg8aqFXlYMCZ19bQPebtnHIi1lMMYQXMK9HV1jlXIniXYktbXs/ITYueOdgsHoC+pVRlNDztMgrDh3XGDDsi5Nk3UgHgptuved8sfnDjgoDcQu7Ui6c82vxtSiI2H0SyfcVOJKbp/Tf/r10sQMA62kEEfpy6t8bYYC+GfnTidyAWmEEi6ePG2jNYr88bI48Ovhfl0fWlaA6Q0NtPlRhZ/vS7mdqKu52VOHRp3DZsnPN+iM3qSDX0aQLlX/p0lA2qsnvRVdoqihaAyUdxPhJA6cN4WQiZ/4nPh11WcV5Kd7fNrUUEyd+IlBy68GL6VPOmVuEBMAGULmDvVaN1K9rpqUl+o9kB9YQjqlj6hUtN/Ggr38R2D6al/g8H7IqlNOvuFvBT8yYvUw1CKASWUA="
os: osx
osx_image: xcode8
