language: java
after_success: echo done
deploy:
  provider: s3
  access_key_id: AKIAJZJVZJJHPCFWHC5A
  secret_access_key:
    secure: hzw7e0YxSyzi7T+GRO8gaAW2EGbTPPdHvIjRdF5v+Tskw7khWSk7eb/+fKtlidsHz+aHiDCivLAWsrfzHjaDvNc1ljjYveYqvUXzxwhqmDP89f9+FpyiMcRu5pngKrS4JhvwrcjCHj3tNoYblZ+sd9tbo4Od7efmjOsK5qM7VikBt62aBG//YUnOnq7g+2uKZgXAUSi/wztspS8OjbcUgTmtdHHMaQweDoe0SV608T7AySvVxz3fe+KAov9zszS5eYGgxyqxtNEsTfiO71gMQ08bn0NRrj0u3+oOm5+GNKNjdE5bd+6xn6rLD5Acdd51remVDSQ4QukoBymbg2HLm//+4P7tvcfNrlpSUwY+UnqwspN3X38e2A3wcIaTIE10Ycv2YU4GTGlpTJUhZ6h+prujt8z6BDqHq7fnv+UOVBJc3D48WuBgt8NFbjBz0dNuTNDW/wgnrjw7Hu4aRNMdH27h2XWmNV3D5o1wQmFNR465e194Ki2nSqBDX3amKw9BuRK9gHo8AgwXg93KiAL2Go4p3UdUImiLba8niaNTApGuVEIHteK9cM5P8Ymz4xpVCkSIXrJ/560w3ovMqRIeFE4OA8pVbUct7Ydp1fE1MTDX17WJPm6cUFM/6FHAgGFb/qXfPF43gAh+Zjm7Bu0vmI8v5ogSVEIZ38axfjn7GtY=
  bucket: bgorven-hello
  skip_cleanup: true
matrix:
  include:
  - os: osx
    osx_image: xcode8
  - os: linux
    jdk: oraclejdk8
    before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y g++-multilib
