/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bven_hello_Native */

#ifndef _Included_org_bven_hello_Native
#define _Included_org_bven_hello_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bven_hello_Native
 * Method:    getGreeting
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_bven_hello_Native_getGreeting
  (JNIEnv *, jclass);

/*
 * Class:     org_bven_hello_Native
 * Method:    sendGreeting
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_bven_hello_Native_sendGreeting
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
